// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBL_nMpafItzYGFq76cnmnI1gHnccQub8',
    appId: '1:51491980663:web:b2a3c8e5b4fad784124d72',
    messagingSenderId: '51491980663',
    projectId: 'studymate-42b3e',
    authDomain: 'studymate-42b3e.firebaseapp.com',
    storageBucket: 'studymate-42b3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjT36Rs2pqWEnJqYWIp_32s69wFgh9vU',
    appId: '1:51491980663:android:9a0c7356ed1418c6124d72',
    messagingSenderId: '51491980663',
    projectId: 'studymate-42b3e',
    storageBucket: 'studymate-42b3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeT1wyRzTyHC2_cF4VQg9n2da6Zh-3580',
    appId: '1:51491980663:ios:c2922f57a2e14721124d72',
    messagingSenderId: '51491980663',
    projectId: 'studymate-42b3e',
    storageBucket: 'studymate-42b3e.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeT1wyRzTyHC2_cF4VQg9n2da6Zh-3580',
    appId: '1:51491980663:ios:c2922f57a2e14721124d72',
    messagingSenderId: '51491980663',
    projectId: 'studymate-42b3e',
    storageBucket: 'studymate-42b3e.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBL_nMpafItzYGFq76cnmnI1gHnccQub8',
    appId: '1:51491980663:web:f6fd1bd56e5e6837124d72',
    messagingSenderId: '51491980663',
    projectId: 'studymate-42b3e',
    authDomain: 'studymate-42b3e.firebaseapp.com',
    storageBucket: 'studymate-42b3e.firebasestorage.app',
  );

}